### ISSUE TITLE
[Enhancement] Disable for certain filetypes

### ISSUE THREAD

**Issue by olimorris** [ivanjermakov/troublesum.nvim#3]
Would be great to disable this for certain filetypes.

If I have a Lazy window opened, I'll see diagnostics:

![Screen Shot 2023-08-13 at 11 16 35@2x](https://github.com/ivanjermakov/troublesum.nvim/assets/9512444/4e498330-e4cc-4e19-a8a3-58d0042598fa)

**Comment by ivanjermakov** [comment]
You can now provide a `config.enabled` as a function to customize summary's appearance.

```lua
{
    "ivanjermakov/troublesum.nvim",
    opts = {
        enabled = function()
            return vim.bo.filetype ~= "lazy"
        end
    }
}
```
